version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: ielts_postgres_dev
    environment:
      POSTGRES_DB: ielts_platform
      POSTGRES_USER: ielts_user
      POSTGRES_PASSWORD: ielts_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations:/docker-entrypoint-initdb.d/
    networks:
      - ielts_network

  redis:
    image: redis:7-alpine
    container_name: ielts_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ielts_network

  adminer:
    image: adminer
    container_name: ielts_adminer_dev
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - ielts_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:

networks:
  ielts_network:
    driver: bridge